# From template: https://github.com/mozilla/cbindgen/blob/HEAD/template.toml
#
# See https://github.com/mozilla/cbindgen/blob/master/docs.md#cbindgentoml
# for detailed documentation of every option here.

language = "C"

pragma_once = true
cpp_compat = true

[export]
include = [
    "allocate_cstring",
    "free_cstring",
]
